# Exploratory Data Analysis Phenotypic Data

This notebook investigates the contents of the phenotypic data from all sites from the ADHD-200 Competition set. 

# Imports

Access all of the packages and files that are important for running this notebook. 
This includes packages, a function, and the phenotypic file for all sites.

## Packages

Since this is only a exploratory data analysis, there aren't very many imports

- `os` for opening files

- `pandas` for dataframes

- `numpy` for arrays

- `matplotlib.pyplot` for plotting

- `seaborn` for customizing plots

In [1]:
import os
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

## File

Import the file to perform exploratory data analysis on. 
This file is located in another folder, so it will need to be accessed from the root folder for this project. 

### get_base_filepath()

Access the filepath for th ebase folder of the project. 
From here, any other asset of the project can be located.

In [2]:
def get_base_filepath():
    '''
    Access the filepath for the base folder of the project
    
    Input: None
    
    Output: The filepath to the root of the folder
    '''
    # Get current directory
    os.path.abspath(os.curdir)

    # Go up a directory level
    os.chdir('..')

    # Set baseline filepath to the project folder directory
    base_folder_filepath = os.path.abspath(os.curdir)
    return base_folder_filepath

### Access file

Update the filepath to include the file's location and open it as a dataframe. 
The index is the column 'ID' which is the subject ID that the row contains information about.

In [3]:
# The folder for the project
base_folder_filepath = get_base_filepath()

# Phenotypic data site folder
filepath = base_folder_filepath + '\\Data\\Phenotypic\\allSubs_testSet_phenotypic_dx.csv'

# Dataframe from filepath
df_pheno = pd.read_csv(filepath, index_col='ID')

# Exploratory Data Analysis

Look at the dataframe and draw conclusions from the insights.

View basic properties of the unchanged dataframe.

In [4]:
df_pheno.shape

(197, 23)

This dataframe includes 197 subjects each with 23 features.

In [5]:
df_pheno.head()

Disclaimer  Site  Gender    Age Handedness DX Secondary Dx    
ID                                                                    
1038415        NaN     1       1  14.92          1  3           ODD  \
1201251        NaN     1       1  12.33          1  3           NaN   
1245758        NaN     1       0   8.58          1  0           NaN   
1253411        NaN     1       1   8.08          1  0           NaN   
1419103        NaN     1       0   9.92          1  0           NaN   

        ADHD Measure ADHD Index Inattentive  ... Verbal IQ Performance IQ   
ID                                           ...                            
1038415            1         52          34  ...     109.0          103.0  \
1201251            1         49          28  ...     115.0          103.0   
1245758            1         35          20  ...     121.0           88.0   
1253411            1         35          19  ...     119.0          106.0   
1419103            1         41          22  ...     124.0           76.0   

         Full2 IQ  Full4 IQ  QC_Rest_1  QC_Rest_2  QC_Rest_3  QC_Rest_4   
ID                                                                        
1038415    -999.0     107.0          1        NaN        NaN        NaN  \
1201251    -999.0     110.0          1        NaN        NaN        NaN   
1245758    -999.0     106.0          1        NaN        NaN        NaN   
1253411    -999.0     114.0          1        NaN        NaN        NaN   
1419103    -999.0     102.0          1        NaN        NaN        NaN   

         QC_Anatomical_1  QC_Anatomical_2  
ID                                         
1038415                1              NaN  
1201251                1              NaN  
1245758                1              NaN  
1253411                1              NaN  
1419103                1              NaN  

[5 rows x 23 columns]

List the 23 columns

In [6]:
df_pheno.columns

Index(['Disclaimer', 'Site', 'Gender', 'Age', 'Handedness', 'DX',
       'Secondary Dx ', 'ADHD Measure', 'ADHD Index', 'Inattentive',
       'Hyper/Impulsive', 'Med Status', 'IQ Measure', 'Verbal IQ',
       'Performance IQ', 'Full2 IQ', 'Full4 IQ', 'QC_Rest_1', 'QC_Rest_2',
       'QC_Rest_3', 'QC_Rest_4', 'QC_Anatomical_1', 'QC_Anatomical_2'],
      dtype='object')

## Filter Dataframe

Not all columns will be useful for making predictions. 

### Unnecessary

These are the features that are least likely to be useful when training a machine learning model. 
A diagnosis should not depend on the quality of the scan.

In [7]:
drop_features = ['Disclaimer',
                 'QC_Rest_1', 'QC_Rest_2', 'QC_Rest_3', 'QC_Rest_4', 
                 'QC_Anatomical_1', 'QC_Anatomical_2']

df_pheno_filtered = df_pheno.copy()
df_pheno_filtered = df_pheno.drop(drop_features, axis=1)

In [8]:
df_pheno_filtered.head()

Site  Gender    Age Handedness DX Secondary Dx  ADHD Measure   
ID                                                                      
1038415     1       1  14.92          1  3           ODD            1  \
1201251     1       1  12.33          1  3           NaN            1   
1245758     1       0   8.58          1  0           NaN            1   
1253411     1       1   8.08          1  0           NaN            1   
1419103     1       0   9.92          1  0           NaN            1   

        ADHD Index Inattentive Hyper/Impulsive Med Status  IQ Measure   
ID                                                                      
1038415         52          34              18          1         3.0  \
1201251         49          28              21          2         3.0   
1245758         35          20              15          1         3.0   
1253411         35          19              16          1         3.0   
1419103         41          22              19          1         3.0   

         Verbal IQ  Performance IQ  Full2 IQ  Full4 IQ  
ID                                                      
1038415      109.0           103.0    -999.0     107.0  
1201251      115.0           103.0    -999.0     110.0  
1245758      121.0            88.0    -999.0     106.0  
1253411      119.0           106.0    -999.0     114.0  
1419103      124.0            76.0    -999.0     102.0

With this change, the number of columns has been reduced to 16. 
This will also make it easier when training since the model has less features to look at.

In [9]:
df_pheno_filtered.shape

(197, 16)

### Holdout

Some of the data was used as a holdout for testing during the competition. 
This data is from the Brown site (Site 2) and has 'pending' for all data directly related to the diagnosis.

In [10]:
df_brown = df_pheno_filtered.loc[df_pheno_filtered['Site'] == 2]
df_pheno_filtered = df_pheno_filtered.drop(df_pheno_filtered.loc[df_pheno_filtered['Site'] == 2].index)
df_brown

Site  Gender    Age Handedness       DX Secondary Dx  ADHD Measure   
ID                                                                          
26001     2       1  16.92          1  pending       pending      pending  \
26002     2       1  15.68          1  pending       pending      pending   
26004     2       0  14.99          1  pending       pending      pending   
26005     2       0  15.16          1  pending       pending      pending   
26009     2       1  16.91          0  pending       pending      pending   
26014     2       0  16.21          1  pending       pending      pending   
26015     2       0  15.20          1  pending       pending      pending   
26016     2       1  16.07          1  pending       pending      pending   
26017     2       0  14.56          1  pending       pending      pending   
26022     2       1  17.83          1  pending       pending      pending   
26024     2       0  17.77          1  pending       pending      pending   
26027     2       0  11.28          1  pending       pending      pending   
26030     2       0  14.51          1  pending       pending      pending   
26039     2       0  14.19          1  pending       pending      pending   
26040     2       0  13.67          1  pending       pending      pending   
26041     2       0  13.68          1  pending       pending      pending   
26042     2       0  13.82          1  pending       pending      pending   
26043     2       0  11.60          1  pending       pending      pending   
26044     2       0   9.32          1  pending       pending      pending   
26045     2       1  14.67          1  pending       pending      pending   
26050     2       0   8.50          1  pending       pending      pending   
26052     2       0  17.87          1  pending       pending      pending   
26053     2       1  15.79          1  pending       pending      pending   
26054     2       0  12.02          1  pending       pending      pending   
26055     2       1  17.74          1  pending       pending      pending   
26057     2       1  12.00          1  pending       pending      pending   

      ADHD Index Inattentive Hyper/Impulsive Med Status  IQ Measure   
ID                                                                    
26001    pending     pending         pending    pending         NaN  \
26002    pending     pending         pending    pending         NaN   
26004    pending     pending         pending    pending         NaN   
26005    pending     pending         pending    pending         NaN   
26009    pending     pending         pending    pending         NaN   
26014    pending     pending         pending    pending         NaN   
26015    pending     pending         pending    pending         NaN   
26016    pending     pending         pending    pending         NaN   
26017    pending     pending         pending    pending         NaN   
26022    pending     pending         pending    pending         NaN   
26024    pending     pending         pending    pending         NaN   
26027    pending     pending         pending    pending         NaN   
26030    pending     pending         pending    pending         NaN   
26039    pending     pending         pending    pending         NaN   
26040    pending     pending         pending    pending         NaN   
26041    pending     pending         pending    pending         NaN   
26042    pending     pending         pending    pending         NaN   
26043    pending     pending         pending    pending         NaN   
26044    pending     pending         pending    pending         NaN   
26045    pending     pending         pending    pending         NaN   
26050    pending     pending         pending    pending         NaN   
26052    pending     pending         pending    pending         NaN   
26053    pending     pending         pending    pending         NaN   
26054    pending     pending         pending    pending         NaN   
2605

There are 26 subjects at the Brown site.

In [11]:
df_brown.shape

(26, 16)

When the Brown subjects are removed from the dataframe, there are 171 subjects remaining.

In [12]:
df_pheno_filtered.shape

(171, 16)

### Targets

These columns directly relate to the diagnosis. 
In the Brown site, these columns are withheld and replaced with 'pending'

In [13]:
targets_features = ['DX', 'Secondary Dx ', 
                    'ADHD Measure', 'ADHD Index', 'Inattentive', 
                    'Hyper/Impulsive', 'Med Status']

df_targets = df_pheno_filtered[targets_features]
df_brown_targets = df_brown[targets_features]
df_pheno_filtered = df_pheno_filtered.drop(targets_features, axis=1)

In [14]:
df_targets.head()

DX Secondary Dx  ADHD Measure ADHD Index Inattentive Hyper/Impulsive   
ID                                                                             
1038415  3           ODD            1         52          34              18  \
1201251  3           NaN            1         49          28              21   
1245758  0           NaN            1         35          20              15   
1253411  0           NaN            1         35          19              16   
1419103  0           NaN            1         41          22              19   

        Med Status  
ID                  
1038415          1  
1201251          2  
1245758          1  
1253411          1  
1419103          1

In [15]:
df_pheno_filtered.head()

Site  Gender    Age Handedness  IQ Measure  Verbal IQ   
ID                                                               
1038415     1       1  14.92          1         3.0      109.0  \
1201251     1       1  12.33          1         3.0      115.0   
1245758     1       0   8.58          1         3.0      121.0   
1253411     1       1   8.08          1         3.0      119.0   
1419103     1       0   9.92          1         3.0      124.0   

         Performance IQ  Full2 IQ  Full4 IQ  
ID                                           
1038415           103.0    -999.0     107.0  
1201251           103.0    -999.0     110.0  
1245758            88.0    -999.0     106.0  
1253411           106.0    -999.0     114.0  
1419103            76.0    -999.0     102.0

## Null values

Look at every column and find the null values or imputed null values (-999)

### Main Dataframe

Focuses on the main dataframe.

#### Gender

There are no null values for 'Gender' and the minimum value is 0, which is a valid input.

In [16]:
df_pheno_filtered['Gender'].isnull().sum()

0

In [17]:
min(df_pheno_filtered['Gender'])

0

#### Age

There are no null values for 'Age' and the lowest age is 7.26

In [18]:
df_pheno_filtered['Age'].isnull().sum()

0

In [19]:
min(df_pheno_filtered['Age'])

7.26

#### Handedness

There are 2 null values for 'Handedness' and one input with a letter.

In [20]:
df_pheno_filtered['Handedness'].isnull().sum()

2

In [21]:
df_pheno_filtered[df_pheno_filtered['Handedness'] == 'L']

Site  Gender   Age Handedness  IQ Measure  Verbal IQ  Performance IQ   
ID                                                                              
4125514     1       1  9.17          L         3.0      136.0           100.0  \

         Full2 IQ  Full4 IQ  
ID                           
4125514    -999.0     121.0

Fix the 'L' value to its numeric value (0).

In [22]:
df_pheno_filtered.loc[df_pheno_filtered['Handedness'] == 'L', 'Handedness'] = 0

#### IQ Measure

There are no null values for 'IQ Measure' and the minimum value is 1, which is a valid input.

In [23]:
df_pheno_filtered['IQ Measure'].isnull().sum()

0

In [24]:
min(df_pheno_filtered['IQ Measure'])

1.0

#### Verbal IQ

There are 60 null values for 'Verbal IQ' and the minimum IQ is 80, which is a valid input.

In [25]:
df_pheno_filtered['Verbal IQ'].isnull().sum()

60

In [26]:
min(df_pheno_filtered['Verbal IQ'])

80.0

#### Performance IQ

There are 60 null values for 'Performance IQ' and the mimimum IQ is 67, which is a valid input.

In [27]:
df_pheno_filtered['Performance IQ'].isnull().sum()

60

In [28]:
min(df_pheno_filtered['Performance IQ'])

67.0

The 60 points where Perforamnce IQ is null are the same 60 points where Verbal IQ is null.

In [43]:
df_pheno_filtered[df_pheno_filtered['Performance IQ'].isnull()]

Site  Gender    Age Handedness  IQ Measure  Verbal IQ  Performance IQ   
ID                                                                             
27000     4       0  20.90          1         5.0        NaN             NaN  \
27003     4       1  17.54          0         5.0        NaN             NaN   
27004     4       1  14.24          0         5.0        NaN             NaN   
27005     4       0  18.65          0         5.0        NaN             NaN   
27007     4       1  16.92          1         5.0        NaN             NaN   
27008     4       1  25.04          1         5.0        NaN             NaN   
27010     4       0  16.45          1         5.0        NaN             NaN   
27011     4       1  20.82          1         5.0        NaN             NaN   
27012     4       0  14.05        NaN         5.0        NaN             NaN   
27015     4       0  20.34          1         5.0        NaN             NaN   
27016     4       0  20.31          1         5.0        NaN             NaN   
27017     4       0  26.31          1         5.0        NaN             NaN   
27018     4       1  19.08        NaN         5.0        NaN             NaN   
27020     4       0  23.59          1         5.0        NaN             NaN   
27021     4       0  20.02          1         5.0        NaN             NaN   
27022     4       0  16.65          1         5.0        NaN             NaN   
27023     4       1  18.08          1         5.0        NaN             NaN   
27024     4       0  20.67          1         5.0        NaN             NaN   
27025     4       0  21.53          1         5.0        NaN             NaN   
27026     4       0  20.55          1         5.0        NaN             NaN   
27028     4       1  14.94          1         5.0        NaN             NaN   
27034     4       1  13.35          1         5.0        NaN             NaN   
27037     4       1  17.74          1         5.0        NaN             NaN   
27040     4       1  17.18          1         5.0        NaN             NaN   
27042     4       1  16.72          1         5.0        NaN             NaN   
21008     5       1  11.28       0.15         2.0        NaN             NaN   
23000     6       0  10.42          1         2.0        NaN             NaN   
23001     6       1   9.33          1         2.0        NaN             NaN   
23002     6       1  10.67          1         2.0        NaN             NaN   
23003     6       1   7.67          1         2.0        NaN             NaN   
23004     6       1   9.33          1         2.0        NaN             NaN   
23005     6       1  11.75          1         2.0        NaN             NaN   
23006     6       0   9.25          1         2.0        NaN             NaN   
23007     6       1  11.08          1         2.0        NaN             NaN   
23008     6       1   9.17          1         2.0        NaN             NaN   
23010     6       0   7.67          1         2.0        NaN             NaN   
23011     6       1   8.92          1         2.0        NaN             NaN   
23012     6       0  11.33          1         2.0        NaN             NaN   
23013     6       1  10.58          1         2.0        NaN             NaN   
23016     6       0  10.25          1         2.0        NaN             NaN   
23017     6       0  12.50          1         2.0        NaN             NaN   
23018     6       0   9.50          1         2.0        NaN             NaN   
23019     6       0   8.08          1         2.0        NaN             NaN   
23020     6       1  11.00          1         2.0        NaN             NaN   
23024     6       0   9.58          1         2.0        NaN             NaN   
23025     6       0   8.33          1         2.0        NaN             NaN   
23026     6       0   8.33          1         2.0        NaN             NaN   
23027     6       1  11.58          1         2.0        NaN             NaN   
23028  

In [29]:
df_pheno_filtered['Full2 IQ'].isnull().sum()

96

In [30]:
min(df_pheno_filtered['Full2 IQ'])

-999.0

In [31]:
df_pheno_filtered[df_pheno_filtered['Full2 IQ'] == -999]

Site  Gender    Age Handedness  IQ Measure  Verbal IQ   
ID                                                               
1038415     1       1  14.92          1         3.0      109.0  \
1201251     1       1  12.33          1         3.0      115.0   
1245758     1       0   8.58          1         3.0      121.0   
1253411     1       1   8.08          1         3.0      119.0   
1419103     1       0   9.92          1         3.0      124.0   
1517058     1       1   9.75          1         3.0      141.0   
1581470     1       1   8.83          1         3.0      111.0   
1784368     1       1   8.92          1         3.0      136.0   
1849382     1       1  11.67          1         3.0      140.0   
1854691     1       0   8.83          1         3.0      117.0   
1883688     1       0   9.08          1         3.0      112.0   
1951511     1       0  11.92          1         3.0      126.0   
1985430     1       0  11.92          1         3.0      146.0   
2024999     1       1  10.33          1         3.0      117.0   
2051479     1       0  13.75          1         3.0      109.0   
2101067     1       0  15.17          1         3.0      117.0   
2275786     1       1   9.50          1         3.0      112.0   
2342030     1       0  10.17          1         3.0      111.0   
2380326     1       0   9.58          1         3.0      103.0   
2380967     1       1  10.00          1         3.0      109.0   
2411995     1       1   9.75          1         3.0      107.0   
2443191     1       1   8.92          1         3.0       99.0   
2488729     1       0  13.75          1         3.0      113.0   
2505328     1       0   8.83          1         3.0       83.0   
2511886     1       1   8.33          1         3.0      133.0   
2528407     1       1   8.92          1         3.0      141.0   
2591713     1       1  10.00          1         3.0      134.0   
2599965     1       1  14.00          1         3.0      101.0   
2628237     1       0  13.00          1         3.0       90.0   
2872641     1       0   8.50          1         3.0      109.0   
3107623     1       0  11.92          1         3.0      121.0   
3124419     1       1   8.75          1         3.0      128.0   
3169448     1       1  11.00          1         3.0      104.0   
3313497     1       1   9.33          1         3.0      111.0   
3320367     1       1  10.67          1         3.0      126.0   
3348989     1       0   8.33          1         3.0      126.0   
3378296     1       1   9.83          1         3.0      141.0   
3407871     1       1  13.33          1         3.0      100.0   
3504058     1       1  13.17          1         3.0      115.0   
3520880     1       1   9.83          1         3.0      140.0   
3559087     1       1  12.58          1         3.0      108.0   
3605062     1       0   8.58          1         3.0      130.0   
3767334     1       1   8.33          1         3.0      112.0   
3834703     1       1  12.92          1         3.0      112.0   
4125514     1       1   9.17          0         3.0      136.0   
6550938     1       1  11.50          1         3.0      146.0   
7591533     1       1  12.42          1         3.0       97.0   
7947495     1       0   9.17          1         3.0      113.0   
8463326     1       0  12.67          1         3.0      108.0   
9190596     1       1  12.50          1         3.0      134.0   
9744150     1       1   9.50          1         3.0      117.0   

         Performance IQ  Full2 IQ  Full4 IQ  
ID                                           
1038415           103.0    -999.0     107.0  
1201251           103.0    -999.0     110.0  
1245758            88.0    -999.0     106.0  
1253411           106.0    -999.0     114.0  
1419103            76.0    -999.0     102.0  
1517058           138.0    -999.0     144.0  
1581470           123.0    -999.0     118.0  
1784368            89.0    -999.0     116.0  
1849382           114.0    -999.0     131.0  
1854

In [32]:
df_pheno_filtered['Full2 IQ'].isnull().sum() + len(df_pheno_filtered[df_pheno_filtered['Full2 IQ'] == -999])

147

In [33]:
df_pheno_filtered['Full4 IQ'].isnull().sum()

27

In [34]:
min(df_pheno_filtered['Full4 IQ'])

77.0

In [35]:
df_targets['Med Status'].isnull().sum()

111

In [38]:
min(df_targets['Med Status'].astype(int))

ValueError: cannot convert float NaN to integer

In [40]:
df_targets['Secondary Dx '] = df_targets['Secondary Dx '].fillna('none')

In [41]:
df_targets['DX'].isnull().sum()

0